### ISSUE TITLE
minor things to improve flexibiltiy

### ISSUE THREAD

**Issue by pfistfl** [dandls/counterfactuals#12]
I am currently playing around with `counterfactuals` a little bit and will use this issue to flag minor things that would 
make extending the package easier.

- https://github.com/dandls/counterfactuals/blob/3d71248008d7b7ba718cb269e15eac4f513e36a1/R/utils_moc.R#L205:
  Switching to `nrow(fitnesses)` allows using more or objectives.

- The different plotting functions seem to have the axis hard coded. Perhaps allow overwriting them or automatically default to first and second if objectives do not exist.

**Comment by dandls** [comment]
Thanks. This got fixed: https://github.com/dandls/counterfactuals/blob/6f34585fcf15794668eff140ea893f82c5aa3b02/R/utils_moc.R#L176
